[package]
name = "zmeng-tauri-commands-scroll-screenshot"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { workspace = true }
serde = { workspace = true }
tauri = { workspace = true }
tokio = { workspace = true }
xcap = { workspace = true }

zmeng-app-utils = { workspace = true }
zmeng-app-scroll-screenshot-service = { workspace = true }
zmeng-app-shared = { workspace = true }
zmeng-global-state = { workspace = true }

[target.'cfg(any(target_os = "macos"))'.dependencies]
scap = { workspace = true }

[target.'cfg(any(target_os = "windows"))'.dependencies]
zmeng-webview = { workspace = true }
