[package]
name = "zmeng-tauri-commands-screenshot"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { workspace = true }
tauri = { workspace = true }
tokio = { workspace = true }
xcap = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }

zmeng-app-shared = { workspace = true }
zmeng-app-os = { workspace = true }
zmeng-app-utils = { workspace = true }
zmeng-capture = { path = "../../zmeng-capture" }
zmeng-webview = { workspace = true }
zmeng-global-state = { workspace = true }

[target.'cfg(any(target_os = "windows"))'.dependencies]
webview2-com = "0.38.0"
windows-core = { version = "0.61" }
windows = { workspace = true }
